
= Theoretical Background

== GMRES
The $m$-th iteration of GMRES builds a Krylov Subspace

$ cal(K)^m(A, r^(0)) = "span"(r^(0), A r^(0), A^2 r^(0), dots, A^(m-1) r^(0)) $

generated by $A$ from $r^(0)$. By demanding that our result $x^(m)$ should come from the same Krylov space $x^(0) + cal(K)^m(A, r^(0))$, we can get a residual

$
  r^(m) := b - A x^(m) & = b - A (x^(0) + sum_(k = 1)^m alpha_k v_k) \
                       & = r^(0) - A sum_(k=1)^m alpha_k v_k in cal(K)^(m+1)(A, r^(0))
$

Therefore, we can freely choose all coefficients $Y = [alpha_1, dots, alpha_m]^T$ optimally to minimize $||r^(m)||_2$.

To get an orthonormal basis for $cal(K)^m(A, r^(0))$, we use the Arnoldi Algorithm, which constructs the basis vectors of $cal(K)^m(A, r^(0))$ iteratively while performing Gram-Schmidt orthogonalization against all existing basis vectors, followed by normalization. The $j$-th iteration returns both a new basis vector $v_(j+1)$ and a vector of coefficients $h_j$, which accounts for the projection of $A v_j$ onto the existing basis vectors, as well as the length of the resulting orthogonal vector prior to normalization.

From these vectors, we obtain an upper Hessenberg matrix $overline(H)_m = [h_1, h_2, dots, h_m] in bb(R)^((m+1) times m)$, which is filled only on its upper diagonal, and on the first diagonal below that.

Applying the following relation from the Arnoldi process:

#quote(block: true)[
  Relation: For $A in bb(R)^(n times n)$ and $V_m$ constructed by $m$ Arnoldi steps, we find: $A V_m = V_(m+1) overline(H)_m$
]

as well as using the fact that multiplication by the matrix with orthonormal columns $V_(m+1)$ does not change the 2-norm of a vector, we find

$ ||r^(m)||_2 & = ||V_(m+1)(beta e_1 - overline(H)_m Y)||_2 = ||beta e_1 - overline(H)_m Y||_2 $

where $beta = ||r^(0)||_2$. So minimizing $||r^(m)||_2$ corresponds to minimizing this expression. After applying Givens Rotations $G = G_m G_(m-1) dots G_1$ to $overline(H)_m$ to triangularize its top $m$ rows without changing the norm of the vector, we are left with

$
  ||beta e_1 - overline(H)_m Y||_2 & = ||G(beta e_1 - overline(H)_m Y)||_2 = ||overline(g) - overline(R) Y||_2 \
                  -> ||r^(m)||_2^2 & = ||g - R Y||_2^2 + |g_(m+1)|^2
$

where $g in bb(R)^m$ and $R in bb(R)^(m times m)$ are the $m$-dimensional upper parts of $overline(g)$ and $overline(R)$. By realizing that only the first part of the $||r^(m)||_2^2$ equation depends on the coefficients $Y$, we find that the minimal residual we can achieve by tuning the coefficients of $Y$ is achieved when:

$
  ||r^(m)||_2^2 = |g_(m+1)|^2 & <=> g - R Y = 0 \
                              & => Y^"optim" = R^(-1) g
$

We can then compute the optimal solution by inserting into $x^(m) = x^(0) + V_m Y^"optim"$.

The method implemented by us, however, uses the fact that we can apply the GMRES algorithm on the fly. Therefore, processing every newly generated column $h_j$ of $overline(H)_m$ separately, applying all $j-1$ previously computed Givens rotations to its $h_(2, j) - h_(j, j)$ entries to make it compatible with all previously processed columns, and computing a final rotation $G_j$ to eliminate the subdiagonal $h_(j+1, j)$ entry for the final rotation.

This is much more efficient because we avoid computing the full upper Hessenberg matrix $overline(H)_m$ in every iteration, and we apply rotations directly to the right-hand side vector, allowing us to monitor the residual norm $|g_(m+1)|$ dynamically without assembling the full solution $x^(m)$, and compute the final solution $x^(j) = x^(0) + V_j Y$ once we hit our desired convergence limit.

== Restarted GMRES
To solve the disadvantage of GMRES, with each iteration becoming more expensive than the previous — a direct result from the dimensionality increase of the Krylov Subspaces — our implementation of GMRES allows restarting, where after $m$ iterations of the $("GMRES")(A, x^(0), b, m, "tol")$ subroutine, only the resulting approximation $x^(m)$ is taken into the next iteration, clearing the previously generated $m$-dimensional Krylov basis.

== Preconditioning
To improve the convergence of our GMRES implementation, we employ various preconditioners and use left-preconditioning. This is motivated by the fact that GMRES converges faster if the eigenvalues of the system matrix $A$ it is applied on are clustered, far away from the origin, and $A$ is close to being normal.

$ A x = b <=> underbrace(M^(-1) A, tilde(A)) x = underbrace(M^(-1) b, tilde(b)) $

The preconditioned problem $tilde(A) x = tilde(b)$ will be easier to solve, and because we use left preconditioning, the solution vector $x$ remains unchanged.

All PCs we used meet the requirements for preconditioners $M$ to be similar to $A$ in the clustered eigenvalue sense, to not be hard to construct, and to be easily invertible.

For the GMRES result, instead of applying $M^(-1)$ directly, we choose to solve $M w = A v_j$ once per Krylov iteration which is equivalent.

=== Jacobi & Gauss Seidel
We implemented the Jacobi and Gauss Seidel preconditioners as simple partial copies of the matrix $A$, where $M_"jacobi" = "diag"(A)$ and $M_"gauss-seidel" = "lower"(A)$ copies the lower triangular component of $A$ (including its main diagonal).

=== Incomplete LU(0) Decomposition
A better choice for a preconditioner is an incomplete LU decomposition, so $M = "ILU"(0) = L' U'$. It is incomplete, as it will not fill up the matrix fully, but forces the preconditioner to have the exact same sparsity pattern as $A$ by dropping any fill-in elements. It is therefore much faster to compute than a full LU decomposition, but retains the property of clustered eigenvalues $lambda_i$ around $1$ as well as providing an easily computable path to the intermediate vectors via forward and backward substitution.

$
          L' U' y & = tilde(x) \
  1) -> quad L' z & = tilde(x) \
  2) -> quad U' y & = z quad "where " z " is the final solution"
$

== CG
For the CG Method, the A-norm $||e_m||_A = sqrt(e_m^T A e_m)$ can be used to gauge the convergence where $e_m := x_m - x$ is the iteration error and $x$ is the "theoretical exact" solution of matrix $A$.

It is important to use this Definition of the Norm for CG, as the algorithm only guarantees a decrease in these metrics, and not in the general 2-Norm $||...||_2$.
